<?php
$flash = $this->flashMessenger();
echo $flash->render('error', array('alert', 'alert-dismissible', 'alert-danger'));
echo $flash->render('info', array('alert', 'alert-dismissible', 'alert-info'));
echo $flash->render('default', array('alert', 'alert-dismissible', 'alert-warning'));
echo $flash->render('success', array('alert', 'alert-dismissible', 'alert-success'));

$title = 'Listagem';
$this->headTitle($title);

?>
<h1><?= $this->escapeHtml($title) ?></h1></br>    
<?php
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form);

?>
<?= $this->formlabel($form->get('status')); ?> <?= $this->formElement($form->get('status')) ?>   
<?= $this->formlabel($form->get('situacao')); ?> <?= $this->formElement($form->get('situacao')) ?>   

<?php
echo $this->formRow($form->get('loginCsrf'));
echo $this->formElement($form->get('submit'));

?>

<?= $this->form()->closeTag($form); ?>

<br/>
<div class="row">   
    <table id="listagem" class="table table-bordered table-hover display responsive" style="width: 100%">
        <thead>
            <tr>
                <th>Nome</th>
                <th class="none">Descricão</th>
                <th>Data Inicial</th>
                <th>Data Fim</th>
                <th>Status</th>
                <th>Situação</th>
                <th class="no-sort all">&nbsp;</th>
            </tr>   
        </thead>
        <tfoot>
            <tr>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Data Inicial</th>
                <th>Data Fim</th>
                <th>Status</th>
                <th>Situação</th>
                <th>&nbsp;</th>
            </tr>   
        </tfoot>
        <?php foreach ($atividades as $atividade) : ?>
            <?php
            $dataInicio = '';
            $dataFim = '';

            if (!empty($atividade->getDataInicio())) {
                $dataInicio = $this->dateFormat(new DateTime($atividade->getDataInicio()), IntlDateFormatter::SHORT, IntlDateFormatter::NONE, "pt_BR");
            }

            if (!empty($atividade->getDataFim())) {
                $dataFim = $this->dateFormat(new DateTime($atividade->getDataFim()), IntlDateFormatter::SHORT, IntlDateFormatter::NONE, "pt_BR");
            }

            ?>
            <tr <?php if ($atividade->getStatus() == Application\Model\Constantes::STATUS_CONCLUIDO): ?>style="background-color: #dff0d8"<?php endif; ?>>
                <td><?= $this->escapeHtml($atividade->getNome()); ?></td>
                <td><?= $this->escapeHtml($atividade->getDescricao()); ?></td>
                <td><?= $dataInicio ?></td>
                <td><?= $dataFim ?></td>
                <td><?= $this->escapeHtml($statusTable->findStatus($atividade->getStatus())->getNome()); ?></td>
                <td><?= $this->escapeHtml($atividade->getLabelSituacao()); ?></td>
                <td>
                    <a class="btn <?php if ($atividade->getSituacao()): ?>btn-success<?php else: ?>btn-danger<?php endif ?>" href="<?php echo $this->url('application', array('action' => 'changeSituacao', 'id' => $atividade->getId())); ?>">
                        <span class="glyphicon glyphicon-off"></span>
                    </a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

</div>


<script>

    $(function () {
        $('#listagem').DataTable({
            responsive: true,
            language: {
                "sEmptyTable": "Nenhum registro encontrado",
                "sInfo": "Mostrando de _START_ até _END_ de _TOTAL_ registros",
                "sInfoEmpty": "Mostrando 0 até 0 de 0 registros",
                "sInfoFiltered": "(Filtrados de _MAX_ registros)",
                "sInfoPostFix": "",
                "sInfoThousands": ".",
                "sLengthMenu": "_MENU_ resultados por página",
                "sLoadingRecords": "Carregando...",
                "sProcessing": "Processando...",
                "sZeroRecords": "Nenhum registro encontrado",
                "sSearch": "Pesquisar",
                "oPaginate": {
                    "sNext": "Próximo",
                    "sPrevious": "Anterior",
                    "sFirst": "Primeiro",
                    "sLast": "Último"
                },
                "oAria": {
                    "sSortAscending": ": Ordenar colunas de forma ascendente",
                    "sSortDescending": ": Ordenar colunas de forma descendente"
                }
            },
            "columnDefs": [{
                    "targets": 'no-sort',
                    "orderable": false,
                }]
        });
    });

</script>